routes/web.php
<?php

use App\Http\Controllers\ArchitectController;
use App\Http\Controllers\BlockCategoryController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/shop', [FrontendController::class, 'products'])->name('shop');
Route::get('shop/{slug}', [FrontendController::class, 'product_details'])->name('shop.details');
Route::get('cart/', [CartController::class, 'cart'])->name('front.cart');
Route::post('add-to-cart/', [CartController::class, 'addToCart'])->name('front.addToCard');
Route::post('update-cart/', [CartController::class, 'updateCart'])->name('front.updateCart');
Route::post('deleteItem/', [CartController::class, 'deleteItem'])->name('front.deleteItem');
Route::post('addToCartWithQty/', [CartController::class, 'addToCartWithQty'])->name('front.addToCartWithQty');
Route::get('checkout/', [CartController::class, 'checkout'])->name('front.checkout');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::resource('product', ProductController::class);
    Route::resource('architect', ArchitectController::class);
    Route::resource('category', CategoryController::class);
    Route::resource('blog', BlogController::class);   
    Route::resource('blog_category', BlockCategoryController::class);   
});

Route::resource('customer', CustomerController::class);
Route::post('/customer-login',[CustomerController::class,'customerLogin'])->name('customer.login');


Route::middleware('customerAuth')->group(function(){
    Route::get('/customer_dashboard', [CustomerController::class, 'customerDashboard'])->name('customer_dashboard');
});

app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use App\Models\ProductModel;
use Illuminate\Support\Facades\Request;

class FrontendController extends Controller
{


    public function index(){
        return view('frontend.home');
    }

    public function products(){
        $arr = ProductModel::orderBy('id', 'DESC')->get();    
        $total_products = $arr->count();
        return view('frontend.products', compact('arr', 'total_products'));
    }

    public function product_details(){

        $slug = Request::segment(count(Request::segments()));        
        //$product = ProductModel::where('slug', $slug)->first();
        $product = ProductModel::with('category', 'architect')->where('slug', $slug)->first();
        $other_images = json_decode($product['otherImage']);        
        
        //$calculated = $product['selling_price']/$product['regular_price']*100;
         
        $calculated = ($product['regular_price']-$product['selling_price'])/$product['regular_price'] * 100;
        $percentage = number_format($calculated,2);
        

        return view('frontend.products_details', compact('product', 'other_images', 'percentage'));
    }
}

resources/views/frontend/cart.blade.php
@extends('frontend.layout')
@section('content')

<!--===========================cart_page part start===================================-->

<section class="cart_page">
  <div class="container">
    <div class="row">
      <div class="card">
        <div class="row">
          <div class="col-md-8 cart">

            @if(Session::has('success'))
            <div class="alert_message alert alert-success" role="alert"><b>{{ Session::get('success') }}</b></div>
            @endif

            @if(Session::has('error'))
            <div class="alert_message alert alert-danger" role="alert"><b>{{ Session::get('error') }}</b></div>
            @endif

            <div class="title">
              <div class="row">
                <div class="col">
                  <h4><b>Shopping Cart</b></h4>
                </div>
                <div class="col align-self-center text-right text-muted">3 items</div>
              </div>
            </div>

            @if(Cart::count()> 0)
              
              @foreach($cartContent as $item)
              
              <div class="row border-top border-bottom">
                <div class="row main align-items-center">
                  <div class="col-2">
                    <img class="img-fluid" src="{{ asset($item->options->productImage)}}">
                  </div>
                  <div class="col">
                    <div class="row text-muted">{{ $item->name }}</div>
                  </div>
                  <div class="col qty">
                    <a href="javascript:void(0)" class="sub" data-id="{{ $item->rowId }}">-</a>
                    <a href="javascript:void(0)" class="border product_qty">{{ $item->qty }}</a>
                    <a  href="javascript:void(0)" class="add" data-id="{{ $item->rowId }}">+</a>
                  </div>
                  <div class="col d-flex"><span>&dollar; {{ $item->price }}</span> <button style="margin-right: 0; display: contents;" onclick="deleteItem('{{ $item->rowId }}')"><span class="close">&#10005;</span></button></div>
                </div>
              </div>
              @endforeach
            @else
              <div class="row border-top border-bottom">
                  <div class="row main align-items-center">
                    <div class="col-12 text-center">
                      <b>Cart is empty</b>
                    </div>                    
                </div>
              </div>                 
            @endif


            
            
            <div class="back-to-shop"><a href="/">&leftarrow;</a><span class="text-muted">Back to shop</span></div>
          </div>
          <div class="col-md-4 summary">
            <div>
              <h5><b>Summary</b></h5>
            </div>
            <hr>
            <div class="row">
              <div class="col" style="padding-left:0;">ITEMS 3</div>
              <div class="col text-right">&dollar; {{ Cart::subtotal() }}</div>
            </div>
            <form>
              <p>SHIPPING</p>
              <select>
                <option class="text-muted">Standard-Delivery- &dollar;{{ Cart::tax() }} </option>
              </select>
              <p>GIVE CODE</p>
              <input placeholder="Enter your code">
            </form>
            <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
              <div class="col">TOTAL PRICE</div>
              <div class="col text-right">&dollar; {{ Cart::total() }}</div>
            </div>
            <a href="{{ route('customer.index') }}"><button class="btn">CHECKOUT</button></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!--===========================cart_page part end===================================-->

<!--===========================client_logo Products part start===================================-->
<section class="client_logo text-center pb-5 pt-5">
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <img src="images/Brand-2.png" alt="img">
      </div>
      <div class="col-sm-3">
        <img src="images/Brand-3.png" alt="img">
      </div>
      <div class="col-sm-3">
        <img src="images/Brand-1.png" alt="img">
      </div>
      <div class="col-sm-3">
        <img src="images/Brand-4.png" alt="img">
      </div>
    </div>
  </div>
</section>
<!--===========================client_logo Products part end===================================-->

<script>

    $('.add').on('click',function(){
        var qtyElement = $(this).closest('.qty').find('.product_qty').text();
        var qtyValue = parseInt(qtyElement);

        if(qtyValue <10){
          var rowId = $(this).data('id');   
          var newQty = qtyValue+1
          $(this).closest('.qty').find('.product_qty').text(newQty);
          updateCart(rowId, newQty);
        }
    });

    $('.sub').on('click',function(){
        var qtyElement = $(this).closest('.qty').find('.product_qty').text();
        var qtyValue = parseInt(qtyElement);

        if(qtyValue > 1){
          var rowId = $(this).data('id');   
          var newQty = qtyValue-1
          $(this).closest('.qty').find('.product_qty').text(newQty);
          updateCart(rowId, newQty);
        }
    });

    function updateCart(rowId, qty){
        //console.log(rowId, qty);

        $.ajax({

          url : "{{ route('front.updateCart') }}",
          type : 'post',
          data : {
            "_token": "{{ csrf_token() }}",
            'rowId' : rowId,
            'qty'   : qty
          },
          dataType : 'json',
          success : function(res){            
              window.location.href= "{{ route('front.cart') }}";            
          }

        });
    }

    function deleteItem(rowId){

      if(confirm("Are you sure want to delete?")){
          $.ajax({
              url : "{{ route('front.deleteItem') }}",
              type : 'post',
              data : {
                "_token": "{{ csrf_token() }}",
                'rowId' : rowId,
              },
              dataType : 'json',
              success : function(res){            
                  window.location.href= "{{ route('front.cart') }}";            
              }
          });
      }
      
    }

    $('.alert_message').delay(2000).fadeOut('slow');

</script>

@endsection

resources/views/frontend/layout.blade.php
<?php
	// echo "<pre>";
	// print_r($categories[2]['id']);
	// echo "</pre>";die;
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Art Design</title>
	<link rel="stylesheet" href="{{asset('assets/art_design/css/bootstrap.min.css')}}">	
	<link rel="stylesheet" href="{{asset('assets/art_design/css/project-1.css')}}">	
	<link rel="stylesheet" href="{{asset('assets/art_design/css/style.css')}}">
	<link rel="stylesheet" href="{{asset('assets/art_design/css/responsive.css')}}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
	<script src="{{asset('assets/art_design/js/jquery-3.7.1.min.js')}}"></script>
</head>

<body>	
	<!--===========================header part start===================================-->
	<header class="header_part">
		<div class="container superNavv">
			<div class="row">
				<div class="col-12">
					<div class="superNav border-bottom py-2 text-light">
				      <div class="container">
				        <div class="row">
				          <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 centerOnMobile">
				            <select  class="me-3 border-0 bg-light">
				              	<option value="en-us">EN-US</option>
				              	<option value="en-us">EN-CA</option>
				              	<option value="en-us">EN-UK</option>
				            </select>
				            <span class="d-none d-lg-inline-block d-md-inline-block d-sm-inline-block d-xs-none me-3"><strong>info@something.com</strong></span>
				            <span class="me-3">
				            	<!-- <i class="fa-solid fa-phone me-1 text-warning"></i> --> 
				            	<span style="font-size: 16px; color: #fa8231; font-weight: 700;"> &#9990;</span>
				            	<strong>+8801-123-123440</strong>
				            </span>
				          </div>
				          <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 d-none d-lg-block d-md-block-d-sm-block d-xs-none text-end">
				            <span class="me-3"><i class="fa-solid fa-truck text-light me-1"></i><a class="text-light" href="#">Shipping</a></span>
				            <span class="me-3"><i class="fa-solid fa-file  text-light me-2"></i><a class="text-light" href="#">Policy</a></span>
				          </div>
				        </div>
				      </div>
				    </div>
				    <nav class="navbar navbar-expand-lg bgdark sticky-top navbar-light shadow-sm ">
				      <div class="container ">
				        <a class="navbar-brand" href="/"><i class="fa-solid fa-shop me-2"></i> 
				        	<img src="{{asset('assets/art_design/images/comlogo.png')}}" alt="LOGO" width="100px" height="40px">				        
				        </a>
				        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
				          <span class="navbar-toggler-icon"></span>
				        </button>
				    
				        <div class="mx-auto my-3 d-lg-none d-sm-block d-xs-block ">
				          <div class="input-group">
				            <span class="border-dark input-group-text text-white"><i class="fa-solid fa-magnifying-glass"></i></span>
				            <input type="text" class="form-control">
				            <button class="btn text-white">Search</button>
				          </div>
				        </div>
				        <div class=" collapse navbar-collapse" id="navbarNavDropdown">
				          <div class="ms-auto d-none d-lg-block">
				            <div class="input-group">
				              <span class="border-dark input-group-text text-white"><i class="fa-solid fa-magnifying-glass"></i></span>
				              <input type="text" class="form-control">
				              <button class="btn text-white">Search</button>
				            </div>
				          </div>
				          <ul class="navbar-nav ms-auto ">
				            <li class="nav-item">
				              <a class="nav-link mx-2 text-uppercase active" aria-current="page" href="/">Home</a>
				            </li>
				            <li class="nav-item">
				              <a class="nav-link mx-2 text-uppercase " aria-current="page" href="#">Offers</a>
				            </li>
				            <li class="nav-item dropdown dropdown-mega position-static">
					            <a class="nav-link mx-2 text-uppercase dropdown-toggle" href="#" data-bs-toggle="dropdown" data-bs-auto-close="outside"> Catalog</a>
					            <div class="dropdown-menu shadow dropdownmega">
					              <div class="mega-content px-4">
					                <div class="container-fluid">
					                  <div class="row">
									
									  
									  	@foreach($categories as $category)										  
					                    <div class="col-3 col-sm-3 col-md-3 py-3">
					                      <h5>{{ $category['name'] }}</h5>
					                      <div class="list-group">
										  	@foreach($products as $product)
												@if($category['id'] == $product['category_id'])
					                        	<a class="list-group-item" href="">{{ $product->name }}</a>
												@endif
												
											@endforeach
					                      </div>
					                    </div>

										@endforeach

					                    <!-- <div class="col-12 col-sm-4 col-md-3 py-4">
					                      	<h5>Coffee Makers</h5>
					                      	<div class="card">
							                  	<img src="{{asset('assets/art_design/images/7.jpg')}}" class="img-fluid" alt="image">
							                  	<div class="card-body">
							                    	<p>Coffee Makers</p>
							                  	</div>
							                </div>
					                    </div>

					                    <div class="col-12 col-sm-4 col-md-3 py-4">
					                      <h5>Stand Mixers</h5>
					                      <div class="list-group">
					                        <a class="list-group-item" href="#">Bowl-Lift Stand Mixers</a>
					                        <a class="list-group-item" href="#">Mixer Attachment</a>
					                        <a class="list-group-item" href="#">Tilt-Head Stand Mixers</a>
					                      </div>
					                    </div>

					                    <div class="col-12 col-sm-12 col-md-3 py-4">
					                      <h5>Espresso Machines</h5>
					                      <div class="list-group">
					                        <a class="list-group-item" href="#">Automatic Espresso</a>
					                        <a class="list-group-item" href="#">Hands-On Espresso</a>
					                        <a class="list-group-item" href="#">Manual Espresso Makers</a>
					                      </div>
					                    </div> -->

					                  </div>
					                </div>
					              </div>
					            </div>
					        </li>
				            <li class="nav-item">
				              <a class="nav-link mx-2 text-uppercase" href="{{ route('shop') }}">Shop</a>
				            </li>
				            <li class="nav-item">
				              <a class="nav-link mx-2 text-uppercase" href="#">Services</a>
				            </li>
				            <li class="nav-item">
				              <a class="nav-link mx-2 text-uppercase" href="#">About</a>
				            </li>
				          </ul>
				          <ul class="navbar-nav ms-auto ">
				            <li class="nav-item">
				              <a class="nav-link mx-2 text-uppercase" href="#">
				              	<!-- <i class="fa-regular fa-heart"></i> -->
				              	<span style="font-size:35px;">&#9825;</span>
				              </a>
				            </li>
				            <li class="nav-item">
				              <a class="nav-link mx-2 text-uppercase minicart-icon" href="javascript:void(0);" >
				              	<!-- <i class="fa-solid fa-cart-shopping "></i> -->
				              	<span style="font-size:30px;">&#128722;</span>
				              </a>
				              	<div class="cart-dropdown">
									<ul>
										<li>
											<div class="mini-cart-thumb">
												<a href="#"><img src="{{asset('assets/art_design/images/41.jpg')}}" alt="img" /></a>
											</div>
											<div class="mini-cart-heading">
												<span>TK 240 x 1</span>
												<h5><a href="#"> Paper Design</a></h5>
											</div>
											<div class="mini-cart-remove">
												<button><i class="ti-close"></i></button>
											</div>
										</li>
										<li>
											<div class="mini-cart-thumb">
												<a href="#"><img src="{{asset('assets/art_design/images/img (6).jpg')}}" alt="img" /></a>
											</div>
											<div class="mini-cart-heading">
												<span>TK 19.00 x 1</span>
												<h5><a href="#">Electric Kettle</a></h5>
											</div>
											<div class="mini-cart-remove">
												<button><i class="ti-close"></i></button>
											</div>
										</li>
									</ul>
									<div class="minicart-total justify-content-between d-flex">
										<span class="pull-left">total : </span>
										<span class="pull-right"> TK 259.00</span>
									</div>
									<div class="mini-cart-checkout">
										<a target="blank" href="cart.html" class="btn-common view-cart">VIEW CART</a>
										<a target="blank" href="" class="btn-common checkout mt-10">CHECK OUT</a>
									</div>
								</div>
				            </li>
				            <li class="nav-item">
				              <a class="nav-link mx-2 text-uppercase my_account" href="javascript:void(0);">
				              	<!-- <i class="fa-solid fa-circle-user"></i> -->
				              	<span style="font-size:30px;"> 👨‍🎓</span>
				              </a>
				              <div class="my_account_dropdown">
									<ul>
										<li><a href="{{ Session::get('role') == 2 ? '/customer_dashboard' : route('customer.index') }}">My Account</a></li>
										<li><a href="{{ route('customer.index') }}">User Login</a></li>
										<li><a href="{{ Session::get('role') == 2 ? '#' : '/customer_dashboard' }}">User Register </a></li>
									</ul>																		
								</div>
				            </li>
				          </ul>
				        </div>
				      </div>
				    </nav> 
				</div>
			</div>
		</div>
	</header> 
	<!--===========================header part end===================================-->
    @yield('content')
	<!--===========================footer part start===================================-->
	<footer class="footer_part pt-5 pb-5">
		<div class="container">
			<div class="row">
				<div class="col-sm-3 contact_info">
					<div class="">
						<h5 class="mb-4">Contact Us</h5>
						<div class="address d-flex gap-3">
							<i class="fa-solid fa-location-dot"></i>
							<p>Majhira, Shajahanpur, Bogura</p>
						</div>
						<div class="phone d-flex gap-3">
							<i class="fa-solid fa-phone-volume"></i>
							<p>+8801928201238</p>
						</div>
						<div class="email d-flex gap-3">
							<i class="fa-solid fa-envelopes-bulk"></i>
							<p>lorem@gmail.com</p>
						</div>
					</div>
					<div class="subscribe">
						<h5>Subscribe Now</h5>
						<p>Subscribe to our newsletterget 10% off your first purchase at here for update</p>
						<input type="text">
					</div>
				</div>
				<div class="col-sm-3 contact_info">
					<div class="about_info ">
						<h5 class="mb-4">About</h5>
						<div class=" ">
							<p><a href="#">Contact Us</a></p>
						</div>
						<div class=" ">
							<p><a href="#">About Us</a></p>
						</div>
						<div class=" ">
							<p><a href="#">Careers</a></p>
						</div>
						<div class=" ">
							<p><a href="#">Flipkart Stories</a></p>
						</div>
						<div class="">
							<p><a href="#">Press</a></p>
						</div>
					</div>
				</div>
				<div class="col-sm-3 contact_info">
					<div class="about_info ">
						<h5 class="mb-4">Help</h5>
						<div class=" ">
							<p><a href="#">Payments </a></p>
						</div>
						<div class=" ">
							<p><a href="#">Shipping </a></p>
						</div>
						<div class=" ">
							<p><a href="#">Cancellation </a></p>
						</div>
						<div class=" ">
							<p><a href="#">FAQ </a></p>
						</div>
						<div class="">
							<p><a href="#">Report Infringement</a></p>
						</div>
					</div>
				</div>
				<div class="col-sm-3 ">
					<div class="about_info ">
						<h5 class="mb-4">Policy</h5>
						<div class=" ">
							<p><a href="#">Return Policy </a></p>
						</div>
						<div class=" ">
							<p><a href="#">Terms Of Use </a></p>
						</div>
						<div class=" ">
							<p><a href="#">Security  </a></p>
						</div>
						<div class=" ">
							<p><a href="#">Privacy  </a></p>
						</div>
						<div class="">
							<p><a href="#">Sitemap</a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="row text-center pt-3 mt-5 footer_bottom">
				<div class="col-12">
					<p>Copyright © 2024 seoexpate </p>
				</div>
			</div>
		</div>
	</footer>
	<!--===========================footer part end===================================-->

	<script src="{{asset('assets/art_design/js/bootstrap.bundle.min.js')}}"></script>
	<script src="{{asset('assets/art_design/js/main.js')}}"></script>

</body>
</html>

resources/views/frontend/products.blade.php
@extends('frontend.layout')
@section('content')

<!--===========================all_products part start===================================-->
<section class="all_products">
		<div class="container">
			<div class="row">
				<aside class="col-md-3 mb-5">				
					<div class="card">
						<article class="filter-group Product_categories">
							<header class="card-header">
								<i class="icon-control fa fa-chevron-down"></i>
								<h6 class="title">Product categories</h6>
							</header>
							<div class="filter-content">
								<div class="card-body">
									<form class="pb-3">
										<div class="input-group">
										  	<input type="text" class="form-control" placeholder="Search">
										  	<div class="input-group-append">
										    	<button class="btn btn-light" type="button"><i class="fa fa-search"></i></button>
										  	</div>
										</div>
									</form>									
									<ul class="navbar-nav ms-auto ">
										<li ><a href="#">Blender Accessories</a></li>
										<li><a href="#">Hand Blenders</a></li>
										<li><a href="#">Portable Blender</a></li>
										<li><a href="#">Coffee Makers</a></li>
										<li><a href="#">Stand Mixers</a></li>
										<li><a href="#">Hands-On Espresso</a></li>
										<li><a href="#">Manual Espresso Makers</a></li>
										<li><a href="#">Espresso Machines</a></li>
										<li><a href="#">Automatic Espresso</a></li>
										<li><a href="#">Tilt-Head Stand Mixers</a></li>
										<li><a href="#">Bowl-Lift Stand Mixers</a></li>
										<li><a href="#">Mixer Attachment</a></li>
									</ul>
								</div> 
							</div>
						</article> 
						<article class="filter-group">
							<header class="card-header">
								<i class="icon-control fa fa-chevron-down"></i>
								<h6 class="title">Product Brands </h6>
							</header>
							<div class="filter-content">
								<div class="card-body">
									<label class="d-flex justify-content-between">
									  <div>
									  	<input type="checkbox">
									  	<span >Espresso </span>
									  </div>
									  <div><span>120</span></div>
									</label>
									<label class="d-flex justify-content-between">
									  <div>
									  	<input type="checkbox">
									  	<span >Blender </span>
									  </div>
									  <div><span>50</span></div>
									</label>
									<label class="d-flex justify-content-between">
									  <div>
									  	<input type="checkbox">
									  	<span >Coffee </span>
									  </div>
									  <div><span>40</span></div>
									</label>
									<label class="d-flex justify-content-between">
									  <div>
									  	<input type="checkbox">
									  	<span >Mixer </span>
									  </div>
									  <div><span>80</span></div>
									</label>
									<label class="d-flex justify-content-between">
									  <div>
									  	<input type="checkbox">
									  	<span >Tilt-Head </span>
									  </div>
									  <div><span>30</span></div>
									</label>
								</div> 
							</div>
						</article> 
						<article class="filter-group filter_price">
							<header class="card-header">
								<i class="icon-control fa fa-chevron-down"></i>
								<h6 class="title">Price range </h6>
							</header>
							<div class="filter-content ">
								<div class="card-body">
									<input type="range" >
									<div class="form-row d-flex mb-4 gap-2">
										<div class="form-group col-md-6">
										  	<label>Min</label>
										  	<input class="form-control" placeholder="$0" type="number">
										</div>
										<div class="form-group text-right col-md-6">
										  	<label>Max</label>
										  	<input class="form-control" placeholder="$1,0000" type="number">
										</div>
									</div> 
									<button class="btn">Filter</button>
								</div>
							</div> 
						</article> 
						<article class="filter-group">
							<header class="card-header">
								<i class="icon-control fa fa-chevron-down"></i>
								<h6 class="title">Product Sizes </h6>
							</header>
							<div class="filter-content">
								<div class="card-body">
								  	<label class=" d-block">
								    	<input type="checkbox">
								    	<span> XS </span>
								  	</label>
								  	<label class="d-block">
								    	<input type="checkbox">
								    	<span> SM </span>
								  	</label>
								  	<label class="d-block">
								    	<input type="checkbox">
								    	<span> LG </span>
								  	</label>
								  	<label class="d-block">
								    	<input type="checkbox">
								    	<span> XXL </span>
								  	</label>
								  	<label class="d-block">
								    	<input type="checkbox">
								    	<span> XL </span>
								  	</label>
								</div>
							</div>
						</article> 
						<article class="filter-group">
							<header class="card-header">
								<i class="icon-control fa fa-chevron-down"></i>
								<h6 class="title">More filters </h6>
							</header>
						</article> 
					</div>
				</aside>
				<main class="col-md-9 our_best_collection Related_Products all_product_gallerys">
					<header class="border-bottom mb-4 pb-3">
						<div class="form-inline">
							<span>{{ $total_products }} Items found </span>
							<select class="mr-2 form-control mt-2">
								<option>Latest items</option>
								<option>Trending</option>
								<option>Most Popular</option>
								<option>Cheapest</option>
							</select>
						</div>
					</header>
					<div class="row">
                        @foreach($arr as $product)
						<div class="col-md-4">
							 <figure class="card card-product-grid">
								<div class="card p-0">
						        	<div class="card-header">
						        		<a href="{{ route('shop.details', ['slug' => $product['slug']])}}"><img src="{{ asset($product['image']) }}" alt="img"></a>
						        	</div>	          
						          <div class="card-body">
						            <div class="rating  col-md-12 col-xl-12">
						            	<p>{{ $product['regular_price'] }}$</p>
									    <div class="rat col-md- col-xl-">
									        <i class="fa-solid fa-star"></i>
									        <i class="fa-solid fa-star"></i>
									        <i class="fa-solid fa-star"></i>
									        <i class="fa-solid fa-star-half-stroke"></i>				        
									        <i class="fa-regular fa-star"></i>
									    </div>
									    <p>{{ $product['name'] }}</p>
									    <p>Dimension : {{ $product['size'] }}</p>
									</div>
						          </div>
						          <div class="woocommerce_cart">
						          	<a href="javascript:void(0)" onclick="addToCart({{ $product['id'] }})">
										<div class="woo_cart">
											<i class="fa-solid fa-cart-plus"></i>
										</div>
									</a>
						          	<div class="woo_cart">
						          		<i class="fa-regular fa-heart"></i>
						          	</div>
						          	<div class="woo_cart">
						          		<i class="fa-solid fa-layer-group"></i>
						          	</div>
						          	<div class="woo_cart">
						          		<a href="product_details_page.html"><i class="fa-solid fa-eye"></i></a>
						          	</div>
						          </div>
						        </div>
							</figure>
						</div>  
						@endforeach
					</div> 
					<nav class="mt-4 cat_pagination" aria-label="Page navigation sample">
					  <ul class="pagination">
					    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
					    <li class="page-item active"><a class="page-link" href="#">1</a></li>
					    <li class="page-item"><a class="page-link" href="#">2</a></li>
					    <li class="page-item"><a class="page-link" href="#">3</a></li>
					    <li class="page-item"><a class="page-link" href="#">Next</a></li>
					  </ul>
					</nav>
				</main>
			</div>
		</div>
	</section>
	<!--===========================all_products part end===================================-->
	<script>
			
		function addToCart(id){
			$.ajax({
				url : "{{ route('front.addToCard') }}",
				type : "post",
				dataType : 'json',
				data : {
					"_token": "{{ csrf_token() }}",
					"id" : id
				},

				success: function(res){

					if(res.status == true){
						window.location.href= "{{ route('front.cart') }}";
					}else{
						alert(res.message);
					}
					
				}
			});
		}

	</script>

@endsection