routes/web.php
<?php

use App\Http\Controllers\ArchitectController;
use App\Http\Controllers\BlockCategoryController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/shop', [FrontendController::class, 'products'])->name('shop');
Route::get('shop/{slug}', [FrontendController::class, 'product_details'])->name('shop.details');
Route::get('cart/', [CartController::class, 'cart'])->name('front.cart');
Route::post('add-to-cart/', [CartController::class, 'addToCart'])->name('front.addToCard');
Route::post('update-cart/', [CartController::class, 'updateCart'])->name('front.updateCart');
Route::post('deleteItem/', [CartController::class, 'deleteItem'])->name('front.deleteItem');
Route::post('addToCartWithQty/', [CartController::class, 'addToCartWithQty'])->name('front.addToCartWithQty');
Route::get('checkout/', [CartController::class, 'checkout'])->name('front.checkout');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::resource('product', ProductController::class);
    Route::resource('architect', ArchitectController::class);
    Route::resource('category', CategoryController::class);
    Route::resource('blog', BlogController::class);   
    Route::resource('blog_category', BlockCategoryController::class);   
});

Route::resource('customer', CustomerController::class);
Route::post('/customer-login',[CustomerController::class,'customerLogin'])->name('customer.login');


Route::middleware('customerAuth')->group(function(){
    Route::get('/customer_dashboard', [CustomerController::class, 'customerDashboard'])->name('customer_dashboard');
});

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Models\CustomerModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        Auth::logout();
        if(Session::get('role') == '2'){            
            return redirect('customer_dashboard');
        }else{
            return view('customer.index');
        }
       
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('customer.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $input = $request->all();
        
        request()->validate([
            'firstName' => 'required|min:3|regex:/^[A-Za-z_-]/',          
            'lastName' => 'required|min:3|regex:/^[A-Za-z_-]/',          
            'email' => 'required|min:3|unique:customers',
            'password' => 'required|min:6',            
            // 'password_confirmation'=> 'min:6|same:password|required_with:password',
        ]);
        //dd($input);

        if(isset($input['image'])){
            $file_name = time().$request->file('image')->getClientOriginalName();
            $request->file('image')->storeAs('images/Architect', $file_name, 'public');
            $input['image'] = "storage/images/Architect/".$file_name;

            if(file_exists($input['old_img'])){
                unlink($input['old_img']);
            }

        }   
                
        $input['password'] = Hash::make($input['password']);

        unset($input['_token'], $input['iAgree']);

        CustomerModel::create($input);
        return redirect('customer_dashboard');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $details = CustomerModel::find($id);
        $input = $request->all();    
          
        
        if (array_key_exists("current_password",$input)){

            $user = CustomerModel::find($input['id']);
            
            $request->validate([
                'current_password' => 'required',
                'new_password' => 'required|confirmed|',
                'new_password_confirmation' => 'required|same:new_password|different:current_password',
            ]);

            #Match The Old Password
            if(Hash::check($input['current_password'], $user['password'])){
                $new_password['password'] = Hash::make($input['new_password']);
                $details->update($new_password);
                return redirect('customer_dashboard')->with('flash_message', 'Password has been changed');
            }else{
                return redirect('customer_dashboard')->with('error', 'Password current password not correct');
            }



        }


        request()->validate([
            'name' => 'min:3|regex:/^[A-Za-z_-]/',          
            'phone' => 'required|numeric|digits_between:8,15',
            'email' => '',
            'date_of_birth' => 'string|min:3|max:64|nullable',
            'gender' => 'string|min:4|max:10|nullable',
            'street_address' => 'string|min:3|max:64|nullable',
            'city' => 'string|min:3|max:64|nullable',
            'state' => 'string|min:3|max:64|nullable',
            'post' => 'string|min:3|max:64|nullable',
            'country' => 'string|min:3|max:64|nullable',
            'ssn' => 'string|min:3|max:64|nullable',
            'company' => 'string|min:3|max:64|nullable',
            'website' => 'string|min:3|max:255|nullable',
            'facebook' => 'string|min:3|max:255|nullable',
            'linkedIn' => 'string|min:3|max:255|nullable',
            'twitter' => 'string|min:3|max:255|nullable',
            'youtube' => 'string|min:3|max:255|nullable',
            'instagram' => 'string|min:3|max:255|nullable',
            'marital_status' => 'min:1|max:1|nullable'
        ]);

        if(isset($input['image'])){
            $file_name = time().$request->file('image')->getClientOriginalName();
            $request->file('image')->storeAs('images/customers', $file_name, 'public');
            $input['image'] = "storage/images/customers/".$file_name;
            
            if(file_exists($input['old_img'])){
                unlink($input['old_img']);
            }

        }   


        unset($input['_token']);
        unset($input['old_img']);

        $details->update($input);
        return redirect('customer_dashboard')->with('flash_message', 'Updated');

        
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }

    public function customerDashboard(){
        $data = CustomerModel::find(Session::get('id'));       
        return view('customer.dashboard')->with('data', $data);
    }

    public function customerLogin(Request $request){        
        
        $input = $request->all();    
        //dd($input);
        $user = CustomerModel::where('email','=',$input['email'])->first();        

        request()->validate([
            'email' => 'required|min:3',
            'password' => 'required',            
        ]);

        $user['role'] = '2';

        if(isset($user['email'])){
            
            Session::put([
                'id' => $user['id'],
                'name' => $user['name'],
                'firstName' => $user['firstName'],
                'role' => $user['role']
            ]);

            return redirect('customer_dashboard');

           
        }else{
            return redirect('customer')->with('error', 'Not matched with customer');
        }


    }
}

resources/views/customer/create.blade.php
@extends('frontend.layout')
@section('content')
<!--===========================register part start===================================-->
	
<section class="user_register_form">
	 <div class="bg-light py-3 py-md-5">
	  <div class="container">
	    <div class="row justify-content-md-center">
	      <div class="col-12 col-md-11 col-lg-8 col-xl-7 col-xxl-6">
	        <div class="bg-white p-4 p-md-5 rounded shadow-sm">
	          <div class="row">
	            <div class="col-12">
	              <div class="text-center mb-5">
	                <a href="#!">
	                  <img src="{{asset('assets/art_design/images/comlogo.png')}}" alt="img" width="185px">
	                </a>
	              </div>
	            </div>
	          </div>
	          <form action="{{ route('customer.store') }}"  method="post">
              @csrf
	            <div class="row gy-3 gy-md-4 overflow-hidden">
	              <div class="col-12">
	                <label for="firstName" class="form-label">First Name <span class="text-danger">*</span></label>
	                <div class="input-group">
	                  <span class="input-group-text">
	                  	<i class="fa-regular fa-address-card"></i>
	                  </span>
	                  <input type="text" class="form-control" name="firstName" id="firstName" required>
	                </div>
                  <span class="text-danger">{{ $errors->first('firstName') }}</span>
	              </div>
	              <div class="col-12">
	                <label for="lastName" class="form-label">Last Name <span class="text-danger">*</span></label>
	                <div class="input-group">
	                  <span class="input-group-text">
	                  	<i class="fa-regular fa-credit-card"></i>
	                  </span>
	                  <input type="text" class="form-control" name="lastName" id="lastName" required>
	                </div>
                  <span class="text-danger">{{ $errors->first('lastName') }}</span>
	              </div>
	              <div class="col-12">
	                <label for="email" class="form-label">Email <span class="text-danger">*</span></label>
	                <div class="input-group">
	                  <span class="input-group-text">
	                  	<i class="fa-regular fa-envelope"></i>
	                  </span>
	                  <input type="email" class="form-control" name="email" id="email" required>
	                </div>
                  <span class="text-danger">{{ $errors->first('email') }}</span>
	              </div>
	              <div class="col-12">
	                <label for="password" class="form-label">Password <span class="text-danger">*</span></label>
	                <div class="input-group">
	                  <span class="input-group-text">
	                    <i class="fa-solid fa-key"></i>
	                  </span>
	                  <input type="password" class="form-control" name="password" id="password" value="" required>
	                </div>
                  <span class="text-danger">{{ $errors->first('password') }}</span>
	              </div>
	              <div class="col-12">
	                <div class="form-check">
	                  <input class="form-check-input" type="checkbox" value="" name="iAgree" id="iAgree" required>
	                  <label class="form-check-label text-secondary" for="iAgree">
	                    I agree to the <a href="#!" class="text-decoration-none">terms and conditions</a>
	                  </label>
	                </div>
	              </div>
	              <div class="col-12">
	                <div class="d-grid">
	                  <button class="btn btn-lg" type="submit">Sign Up</button>
	                </div>
	              </div>
	            </div>
	          </form>
	          <div class="row">
	            <div class="col-12">
	              <hr class="mt-5 mb-4 border-secondary-subtle">
	              <p class="m-0 text-secondary text-center">Already have an account? <a href="loin.html" class="text-decoration-none">Sign in</a></p>
	            </div>
	          </div>
	        </div>
	      </div>
	    </div>
	  </div>
	 </div>
	</section>				

	<!--===========================register part end===================================-->
  @endsection

resources/views/customer/index.blade.php
@extends('frontend.layout')
@section('content')

<section class=" user_register_form">
  <div class="container py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-10">
        <div class="card rounded-3 text-black">
          <div class="row g-0">
            <div class="col-lg-6">
              <div class="card-body p-md-5 mx-md-4">
                <div class="text-center">
                  <img src="{{asset('assets/art_design/images/comlogo.png')}}" alt="logo">
                  <h4 class="mt-1 mb-5 pb-1">Welcome To Login </h4>
                </div>
                <form method="post" action="{{ route('customer.login')}}">
                  {!! csrf_field() !!}
                  <p>Please login to your account</p>
                  <div class="form-outline mb-4">
                    <label class="form-label" for="user">Username</label>
                    <input type="email" name="email" id="user" class="form-control" placeholder="Phone number or email address" />
                  </div>
                  <div class="form-outline mb-4">
                    <label class="form-label" for="pass">Password</label>
                    <input type="password" name="password" id="pass" class="form-control" />
                  </div>
                  <div class="text-center pt-1 mb-5 pb-1 loginbtn">
                    <button class="btn mb-3" type="submit">Log in</button>
                    <a class="text-muted" href="#!">Forgot password?</a>
                  </div>                  
                </form>
                <div class="d-flex align-items-center justify-content-center pb-4">
                    <p class="mb-0 me-2">Don't have an account?</p>
                    <a href="register.html"><button type="button" class="btn btn-outline-danger">Create new</button></a>
                  </div>
              </div>
            </div>
            <div class="col-lg-6 d-flex align-items-center btnblock">
              <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                <h4 class="mb-4">We are more than just a company</h4>
                <p class="small mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                  exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

@endsection

resources/views/customer/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Customer Dashboard</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon"> -->

    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{{asset('assets/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('assets/vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
    <link href="{{asset('assets/vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
    <link href="{{asset('assets/vendor/quill/quill.snow.css')}}" rel="stylesheet">
    <link href="{{asset('assets/vendor/quill/quill.bubble.css')}}" rel="stylesheet">
    <link href="{{asset('assets/vendor/remixicon/remixicon.css')}}" rel="stylesheet">
    <link href="{{asset('assets/vendor/simple-datatables/style.css')}}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <link href="{{asset('assets/css/style.css')}}" rel="stylesheet">
</head>

<body>
    
    @livewire('navigation-menu')
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link" href="">
                    <i class="bi bi-grid"></i>
                    <span>My Dashboard</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="">
                    <i class="bi bi-grid"></i>
                    <span>My Order</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="">
                    <i class="bi bi-grid"></i>
                    <span>Wallet</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="">
                    <i class="bi bi-grid"></i>
                    <span>My Review</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="">
                    <i class="bi bi-grid"></i>
                    <span>My Wishlist</span>
                </a>
            </li>          
            

        </ul>

    </aside><!-- End Sidebar-->

    @yield('content')

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <script src="{{asset('assets/vendor/apexcharts/apexcharts.min.js')}}"></script>
    <script src="{{asset('assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{asset('assets/vendor/chart.js/chart.umd.js')}}"></script>
    <script src="{{asset('assets/vendor/echarts/echarts.min.js')}}"></script>
    <script src="{{asset('assets/vendor/quill/quill.min.js')}}"></script>
    <script src="{{asset('assets/vendor/simple-datatables/simple-datatables.js')}}"></script>
    <script src="{{asset('assets/vendor/tinymce/tinymce.min.js')}}"></script>
    <script src="{{asset('assets/vendor/php-email-form/validate.js')}}"></script>

    <script src="{{asset('assets/js/main.js')}}"></script>

</body>

</html>